<?php

$lang['Stripped & Columns Theme Configuration'] = 'Stripped & Columns, Page de configuration';
$lang['Page'] = 'Page';
$lang['Displaying options'] = "Options d'affichage";
$lang['Width of columns'] = "Largeur des colonnes";
$lang['Width of thumbnails'] = "Largeur des miniatures";
$lang['it need to be inferior than the width of columns'] = "cette largeur doit être strictement inférieure à celle des colonnes";
$lang['The thumbnails can be generated by the theme'] = "Les miniatures peuvent être générées par le thème";
$lang['option thumbnail generated'] = "générer toutes les miniatures : elles auront toutes la largeur indiquée dans \"Largeur des miniatures\" avec les proportions d'origines conservées";
$lang['option thumbnail auto'] = "générer uniquement les miniatures ayant une largeur inférieure à celle indiquée dans \"Largeur des miniatures\" : cela permet notamment de générer par Piwigo des miniatures plus grosses pour avoir une variation de hauteur";
$lang['option thumbnail piwigo'] = "ne rien générer : les miniatures seront celles de Piwigo";
?>