<?php

$lang['Stripped & Columns Theme Configuration'] = 'Stripped & Columns, Сторінка конфігурації';
$lang['Page'] = 'Сторінка';
$lang['color main'] = "Не сірим кольором :";
$lang['Displaying options'] = "Показати варіанти";
$lang['Width of columns'] = "Ширина стовпців";
$lang['Width of thumbnails'] = "Ширина мініатюри";
$lang['it need to be inferior than the width of columns'] = "вона повинна суворо поступаютися ширину стовпців";
$lang['The thumbnails can be generated by the theme'] = "Мініатюри можуть бути отримані на тему";
$lang['option thumbnail generated'] = "створити всі ескізи: вони будуть мати все ту ж ширину, \"Ширина мініатюри\", по відношенню до оригінальних пропорцій";
$lang['option thumbnail auto'] = "створювати тільки ескізи з шириною менше, ніж зазначено в \"Ширина мініатюри\": він дозволяє генерувати у вигляді мініатюр Piwigo набагато більше, аби зміни висоту(є більш привабливим)";
$lang['option thumbnail piwigo'] = "генерувати нічого: мініатюри будуть одними з Piwigo";
?>