<div class="titrePage">
  <h2>{'Stripped & Columns Theme Configuration'|@translate}</h2>
</div>
<form method="post" class="properties" action="" ENCTYPE="multipart/form-data" name="form" class="properties">
<div id="configContent">
  <fieldset>
    <legend>{'Displaying options'|@translate}</legend>
    <ul>
    <li>
      <label for="column_width"><span class="property">{'Width of columns'|@translate}</span>&nbsp;</label>
      <input type="text" id="column_width" name="f_column_width" size="4" maxlength="4" value="{$options.column_width}" style="text-align:center;">
      &nbsp;px</li>
    <li>
      <label for="column_width"><span class="property">{'Width of thumbnails'|@translate}</span>&nbsp;</label>
      <input type="text" id="column_width" name="f_thumbnail_width" size="4" maxlength="4" value="{$options.thumbnail_width}" style="text-align:center;">
      &nbsp;px&nbsp;{'it need to be inferior than the width of columns'|@translate}</li>
    <li>
      <label for="thumbnail">{'The thumbnails can be generated by the theme'|@translate}</label>
      </p>
      <label>
        <input type="radio" name="f_thumbnail" id="thumbnail" value="generated"  {if $options.thumbnail=="generated"}checked{/if}>
        &nbsp;{'option thumbnail generated'|@translate}</label>
      <br>
      <label>
        <input type="radio" name="f_thumbnail" id="thumbnail" value="auto" {if $options.thumbnail=="auto"}checked{/if}>
        &nbsp;{'option thumbnail auto'|@translate}</label>
      <br>
      <label>
        <input type="radio" name="f_thumbnail" id="thumbnail" value="piwigo" {if $options.thumbnail=="piwigo"}checked{/if}>
        &nbsp;{'option thumbnail piwigo'|@translate}</label>
      <br>
    </li>
  </fieldset>
  </ul>
</div>
<p>
  <input class="submit" type="submit" value="{'Submit'|@translate}" name="submit_stripped_black_bloc" />
</p>
</form>
