<?php

$lang['Stripped & Columns Theme Configuration'] = 'Stripped & Columns, Configuration Page';
$lang['Page'] = 'Page';
$lang['color main'] = "Not grey color :";
$lang['Displaying options'] = "Display options";
$lang['Width of columns'] = "Width of columns";
$lang['Width of thumbnails'] = "Width of thumbnails";
$lang['it need to be inferior than the width of columns'] = "it needs to be strictly inferior than the width of columns";
$lang['The thumbnails can be generated by the theme'] = "The thumbnails can be generated by the theme";
$lang['option thumbnail generated'] = "generate all the thumbnails : they will have all the same width, the \"Width of thumbnails\", with respect to the original proportions";
$lang['option thumbnail auto'] = "generate only the thumbnails with a width lower than that indicated in  \"Width of thumbnails\" : it allows you to generate by Piwigo thumbnails much larger to have a variation of height (much more attractive)";
$lang['option thumbnail piwigo'] = "generate nothing: thumbnails will be the ones of Piwigo";
?>